apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycas-webapp
  labels:
    app: mycas-webapp
spec:
  replicas: 1  # Single replica
  selector:
    matchLabels:
      app: mycas-webapp
  template:
    metadata:
      name: mycas-webapp
      labels:
        app: mycas-webapp
    spec:
      containers:
        - name: mycas-webapp
          image: pdek1991/mycas_webapp:v1
#          imagePullPolicy: Always
          command: ["/bin/sh", "-c", "sleep 1d"]
          resources:
            requests:
              cpu: "100m"      # Minimum CPU request (0.1 vCPU)
              memory: "128Mi"  # Minimum memory request (128MB)
            limits:
              cpu: "250m"      # Limit to 0.25 vCPU
              memory: "256Mi"  # Limit to 256MB
          ports:
            - containerPort: 8080  # Flask default port
---
apiVersion: v1
kind: Service
metadata:
  name: mycas-webapp
spec:
  selector:
    app: mycas-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # Change to NodePort or LoadBalancer if external access is needed

