apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: client-network-policy
  namespace: mycas
spec:
  podSelector:
    matchLabels:
      app: mycas-client
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:   
    - namespaceSelector:
        matchLabels:
          app: mycas
      podSelector:
        matchLabels:
          app: mycas-cycler
    ports:
        - protocol: UDP
          port: 5050
  - from:   
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 5050
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          app: mycas
      podSelector:
        matchLabels:
          app: mycas-cycler
    ports:
        - protocol: UDP
          port: 5050

  - to:  
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
        - protocol: TCP
          port: 5050