apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1  # Corrected name field
              secret: cHJhc2hhbnRLYWRhbXRoaXNpc215ZW5jcnlwdGlvbjE=
      - identity: {}  # Fallback to unencrypted if the above fails
