apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: mycas  
spec:
  limits:
  - min:
      cpu: "50m"         
      memory: "64Mi"
    max:
      cpu: "500m"         
      memory: "512Mi"
    default:   
      cpu: "50m"         
      memory: "128Mi"     
    defaultRequest:  
      cpu: "50m"         
      memory: "128Mi"     
    type: Container
